gearbox_auth:
    resource: "@GearboxAuthBundle/Resources/config/routing.xml"
    prefix:   /

gearbox_client:
    resource: "@GearboxClientBundle/Resources/config/routing.xml"
    prefix:   /

gearbox_media:
    resource: "@GearboxMediaBundle/Resources/config/routing.xml"
    prefix:   /